# https://docs.github.com/github/administering-a-repository/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
