# Generated by Django 2.2.28 on 2023-01-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvitem',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='rvitem',
            name='original_media',
        ),
        migrations.RemoveField(
            model_name='rvitem',
            name='primary_media',
        ),
        migrations.RemoveField(
            model_name='rvitem',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='rvdomain',
            name='alt_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rvdomain',
            name='blurb',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='rvdomain',
            name='display_name',
            field=models.CharField(default='RearVue', max_length=128),
        ),
        migrations.AlterField(
            model_name='rvdomain',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rvsite.RVItem'),
        ),
        migrations.AlterField(
            model_name='rvitem',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rvitem',
            name='raw_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rvitem',
            name='remote_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rvitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='auth_secret',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='auth_token',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='max_update_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='profile_pic',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rvservice',
            name='username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='RVMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_media', models.CharField(blank=True, default='', max_length=256)),
                ('primary_media', models.CharField(blank=True, default='', max_length=256)),
                ('media_type', models.IntegerField(choices=[(0, 'None'), (1, 'Image'), (2, 'Video')], default=0)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=256)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rvsite.RVItem')),
            ],
        ),
    ]
