# Generated by Django 2.2.28 on 2023-01-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0002_auto_20230103_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvservice',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
