# Generated by Django 3.2.16 on 2023-01-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0003_rvservice_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvitem',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rvitem',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rvservice',
            name='hide_unmoderated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RVLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=256)),
                ('context', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rvsite.rvitem')),
            ],
        ),
    ]
