# Generated by Django 3.2.16 on 2023-01-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0004_auto_20230116_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvlink',
            name='url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
