# Generated by Django 3.2.16 on 2023-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0005_rvlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvdomain',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
