# Generated by Django 3.2.18 on 2023-02-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0006_rvdomain_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvlink',
            name='image',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='rvlink',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
