# Generated by Django 3.2.18 on 2023-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0007_auto_20230218_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvlink',
            old_name='context',
            new_name='is_context',
        ),
    ]
