# Generated by Django 5.0.4 on 2024-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvsite', '0009_alter_rvmedia_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rvitem',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='rvitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, db_index=True),
        ),
    ]
