# Generated by Django 5.0.14 on 2025-09-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rvsite", "0010_alter_rvitem_options_rvitem_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="rvservice",
            name="extra_data",
            field=models.BinaryField(blank=True, default=b""),
        ),
    ]
